### ISSUE TITLE
OpenAPI const support

### ISSUE THREAD

**Issue by alex-dixon** [sukovanej/schema-openapi#135]
Hi. It looks like this might not be supported? https://swagger.io/docs/specification/data-models/keywords/. I've seen several tools like https://editor.swagger.io/ not like it.

https://github.com/sukovanej/schema-openapi/blob/da03fc2b335944a98d29b5e32c88576e97d84998/src/compiler.ts#L85

I think `enum: [ "foo" ]` will produce the desired effect though.

**Comment by sukovanej** [comment]
I will check that. In the tests, I'm using a `@apidevtools/swagger-parser` validation to check the produced spec ok, but it's possible I accidentally didn't cover the `const` case.

**Comment by sukovanej** [comment]
You were right. I didn't cover the case and the swagger-parse says it's invalid, not sure where I found the `const` 🤷. Thanks a lot for the catch. I'm gonna release the fixed version and then update `effect-http`.
