### ISSUE TITLE
Add description annotations to the generated JSON Schema

### ISSUE THREAD

**Issue by hannesj** [sukovanej/schema-openapi#33]
Would you be open to adding the descriptions, added to the schema with `S.description` annotations, for the types used in the request and response objects? The type `OpenAPISchemaType` supports an optional description string already, and we could easily fetch it from the AST [here](https://github.com/sukovanej/schema-openapi/blob/master/src/compiler.ts#LL68C4-L68C4) and add it to the returned object.

**Comment by sukovanej** [comment]
Sure thing! I already thought about that and maybe even started but for some reason didn't finish it. Feel free to open a MR if you already have an idea how to extend the compiler. Otherwise I'll get to it during the weekend.

**Comment by sukovanej** [comment]
Released in [0.2](https://github.com/sukovanej/schema-openapi/releases/tag/v0.2.0). I'm gonna do the corresponding update in (effect-http)[https://github.com/sukovanej/effect-http] as well and release it during today.

**Comment by sukovanej** [comment]
[effect-http 0.11](https://github.com/sukovanej/effect-http/releases/tag/v0.11.0).

**Comment by hannesj** [comment]
Thanks for the quick response. I made a follow-up pr with extraction of the functionality to a separate method, which is run against all returned objects in https://github.com/sukovanej/schema-openapi/pull/38. I think it's a bit cleaner to separate the responsibilities as the description is common to all branches of the switch.
